const ROLE_DEFS={
  classmate:{name:'クラスメイト',side:'real',image:'../../role_classmate.png',max:10,desc:'特別な能力はありません。話し合いからニセ転校生を見つけます。'},
  fake:{name:'ニセ転校生',side:'fake',image:'../../role_fake_transfer_student.png',max:2,desc:'夜にほかのニセ転校生がいるかどうか確認します。'},
  president:{name:'学級委員',side:'real',image:'../../role_class_representative.png',max:1,desc:'夜に「プレイヤー1人の役職を見る」か「お休みのカード2枚を見る」のどちらかを選びます。'},
  observer:{name:'観察係',side:'real',image:'../../role_observer.png',max:1,desc:'夜にプレイヤー2人を選び、その2人が同じ陣営か違う陣営かを確認します。'},
  swapper:{name:'席替え係',side:'real',image:'../../role_seat_changer.png',max:1,desc:'夜にプレイヤー1人を選び、自分の役職カードと入れ替えます。交換しないこともできます。入れ替えた場合は新しい役職を確認し、その役職になります。'},
  collaborator:{name:'秘密の協力者',side:'fake',image:'../../role_secret_collaborator.png',max:1,desc:'ニセ転校生陣営です。夜の行動はありません。ニセ転校生側が勝てば一緒に勝利します。誰がニセ転校生かは知りません。'}
};
const PLAYER_ICONS=['🐶','🐱','🐰','🐼','🦊','🐸','🐧','🐯','🐨','🐵','🦁','🐹'];
const roleKeys=Object.keys(ROLE_DEFS);
const app=document.getElementById('app');
const state={screen:'title',playerCount:3,players:[],roleCounts:{},deck:[],rest:[],initialRoles:[],finalRoles:[],revealIndex:0,nightIndex:0,voteIndex:0,votes:[],coverNext:null,timerSeconds:180,timerRemaining:180,timerId:null,modal:null};
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function needCards(){return state.playerCount+2;} function totalCards(){return Object.values(state.roleCounts).reduce((a,b)=>a+b,0);} function sideLabel(r){return ROLE_DEFS[r].side==='real'?'ホンモノサイド':'ニセモノサイド';}
function formatTime(s){return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;}
function ensurePlayers(){while(state.players.length<state.playerCount){const i=state.players.length;const used=new Set(state.players.map(p=>p.icon));state.players.push({name:`プレイヤー${i+1}`,icon:PLAYER_ICONS.find(x=>!used.has(x))||PLAYER_ICONS[i%PLAYER_ICONS.length]});}state.players=state.players.slice(0,state.playerCount);}
function setBaseRoles(){const c={classmate:0,fake:2,president:0,observer:0,swapper:0,collaborator:0};let r=needCards()-2;for(const k of ['president','observer','swapper','collaborator']){if(r>1){c[k]=1;r--;}}c.classmate=r;state.roleCounts=c;}
function topNav(){return `<div class="top-nav"><a class="back-home" href="../../">← 放課後ゲーム部</a></div>`;} function brand(){return `<img class="game-brand" src="../../nise_transfer_student_logo.png" alt="ニセ転校生を探せ！">`;} function heading(t,s=''){return `<h1 class="title">${t}</h1>${s?`<p class="subtitle">${s}</p>`:''}`;} function helpButtons(){return `<div class="topbar"><button class="btn secondary" data-open="roles">役職確認</button><button class="btn secondary" data-open="reg">レギュ確認</button></div>`;}
function stopTimer(){if(state.timerId){clearInterval(state.timerId);state.timerId=null;}} function go(s){stopTimer();state.screen=s;render();} function render(){app.innerHTML=screenHtml();bind();if(state.modal)renderModal();}
function screenHtml(){return ({title:titleScreen,count:countScreen,players:playersScreen,roles:rolesScreen,revealPass:revealPassScreen,revealRole:revealRoleScreen,cover:coverScreen,nightIntro:nightIntroScreen,nightPass:nightPassScreen,nightAction:nightActionScreen,discussion:discussionScreen,votePass:votePassScreen,vote:voteScreen,result:resultScreen}[state.screen]||(()=>`${topNav()}<div class="card">画面エラー</div>`))();}
function titleScreen(){return `${topNav()}<div class="card game-title-card">${brand()}<p class="subtitle">クラスにまぎれたニセ転校生を見つけよう！</p><div class="stack"><button class="btn yellow full" id="startSetup">ゲームをはじめる</button><button class="btn secondary full" data-open="roles">役職をみる</button></div></div>`;}
function countScreen(){return `${topNav()}${brand()}${heading('何人で遊ぶ？','3〜10人に対応')}<div class="card stack"><div class="grid3">${[3,4,5,6,7,8,9,10].map(n=>`<button class="btn choice ${state.playerCount===n?'selected':''}" data-count="${n}">${n}人</button>`).join('')}</div><button class="btn full" id="toPlayers">つぎへ</button></div>`;}
function playersScreen(){ensurePlayers();const used=state.players.map(p=>p.icon);return `${topNav()}${heading('参加者を登録','名前とアイコンを決めよう')}<div class="stack">${state.players.map((p,i)=>`<div class="card player-card"><div class="player-line"><div class="avatar">${p.icon}</div><input aria-label="プレイヤー${i+1}の名前" data-name="${i}" value="${esc(p.name)}" maxlength="12"></div><div class="icon-pick">${PLAYER_ICONS.map(ic=>`<button class="icon-btn ${p.icon===ic?'selected':''}" data-icon-player="${i}" data-icon="${ic}" ${p.icon!==ic&&used.includes(ic)?'disabled':''}>${ic}</button>`).join('')}</div></div>`).join('')}</div><div class="row"><button class="btn secondary" id="backCount">戻る</button><button class="btn" id="toRoles">役職を決める</button></div>`;}
function rolesScreen(){const valid=totalCards()===needCards()&&state.roleCounts.fake===2;return `${topNav()}${heading('使用する役職','人数＋お休み2枚ぶんのカードを選ぶ')}<div class="card"><div class="note ${valid?'success':'warning'}">必要：${needCards()}枚 ／ 現在：${totalCards()}枚<br>ニセ転校生は2枚固定です。</div>${roleKeys.map(k=>{const d=ROLE_DEFS[k];return `<div class="role-row"><img class="role-thumb" src="${d.image}" alt=""><div><div class="role-title">${d.name}</div><span class="side-tag ${d.side}">${sideLabel(k)}</span></div><button class="btn secondary" data-role-minus="${k}" ${k==='fake'||state.roleCounts[k]<=0?'disabled':''}>−</button><span class="count">${state.roleCounts[k]}</span><button class="btn secondary" data-role-plus="${k}" ${k==='fake'||state.roleCounts[k]>=d.max?'disabled':''}>＋</button></div>`}).join('')}</div><div class="row"><button class="btn secondary" id="backPlayers">戻る</button><button class="btn" id="dealRoles" ${valid?'':'disabled'}>役職を配る</button></div>`;}
function revealPassScreen(){const p=state.players[state.revealIndex];return `${topNav()}${heading('役職確認',`${state.revealIndex+1} / ${state.playerCount}`)}<div class="privacy-screen"><div><div class="avatar large">${p.icon}</div><h2>${esc(p.name)}さんに<br>スマホを渡してください</h2><p>ほかの人は画面を見ないでね。</p><button class="btn yellow hold" id="holdReveal">長押しして役職を見る</button></div></div>`;}
function revealRoleScreen(){const r=state.initialRoles[state.revealIndex],d=ROLE_DEFS[r];return `${topNav()}<div class="card role-reveal"><span class="side-tag ${d.side}">${sideLabel(r)}</span><img class="role-card-large" src="${d.image}" alt="${d.name}"><p class="role-desc">${d.desc}</p><button class="btn full" id="hideRole">役職をかくす</button></div>`;}
function coverScreen(){return `${topNav()}<div class="privacy-screen"><div><h2>画面を伏せてください</h2><p>内容が見えない状態にしてから、次の人へ渡そう。</p><button class="btn yellow" id="coverNext">次へ</button></div></div>`;}
function nightIntroScreen(){return `${topNav()}${helpButtons()}${heading('夜の時間','1人ずつ自分だけで確認します')}<div class="card stack"><p>夜の処理は <strong>ニセ転校生 → 学級委員 → 観察係 → 席替え係</strong> の情報関係になるよう処理します。</p><div class="note">クラスメイトと秘密の協力者には夜の行動はありません。</div><button class="btn" id="beginNight">夜を始める</button></div>`;}
function nightPassScreen(){const p=state.players[state.nightIndex];return `${topNav()}${heading('夜の行動',`${state.nightIndex+1} / ${state.playerCount}`)}<div class="privacy-screen"><div><div class="avatar large">${p.icon}</div><h2>${esc(p.name)}さんに<br>スマホを渡してください</h2><p>自分の名前を確認してから進んでね。</p><button class="btn yellow hold" id="holdNight">長押しして夜を確認</button></div></div>`;}
function nightActionScreen(){const i=state.nightIndex,r=state.initialRoles[i],d=ROLE_DEFS[r];let body='';if(r==='classmate'||r==='collaborator'){body=`<div class="card role-reveal"><span class="night-role ${d.side==='fake'?'fake':''}">${d.name}</span><img class="role-card-large" src="${d.image}" alt="${d.name}"><h2>夜の行動はありません</h2><button class="btn full" id="nightDone">確認した</button></div>`;}else if(r==='fake'){const another=state.initialRoles.some((x,j)=>j!==i&&x==='fake');body=`<div class="card role-reveal"><span class="night-role fake">ニセ転校生</span><img class="role-card-large" src="${d.image}" alt="ニセ転校生"><h2>${another?'ほかにもニセ転校生がいます':'ほかのニセ転校生はいません'}</h2><p class="role-desc">相手が誰かは表示されません。</p><button class="btn full" id="nightDone">確認した</button></div>`;}else if(r==='president'){body=`<div class="card stack"><h2>学級委員</h2><p>どちらか1つを選びます。</p><button class="btn" id="presidentPlayer">プレイヤー1人を見る</button><button class="btn secondary" id="presidentRest">お休み2枚を見る</button></div>`;}else if(r==='observer'){body=`<div class="card stack"><h2>観察係</h2><p>自分以外から2人を選び、同じサイドか確認します。</p><div id="observerChoices" class="grid2">${state.players.map((p,j)=>j===i?'':`<button class="btn choice" data-observe="${j}">${esc(p.name)}</button>`).join('')}</div><button class="btn" id="observerCheck" disabled>確認する</button></div>`;}else if(r==='swapper'){body=`<div class="card stack"><h2>席替え係</h2><p>1人を選んで自分のカードと交換します。交換しなくてもOKです。</p><div class="grid2">${state.players.map((p,j)=>j===i?'':`<button class="btn choice" data-swap="${j}">${esc(p.name)}</button>`).join('')}</div><button class="btn secondary" id="noSwap">交換しない</button></div>`;}return `${topNav()}${helpButtons()}${heading(`${esc(state.players[i].name)}さんの夜`)}${body}`;}
function discussionScreen(){return `${topNav()}${helpButtons()}${heading('話し合い','ニセ転校生は誰？')}<div class="card"><div id="timer" class="timer ${state.timerRemaining<=10?'low':''}">${formatTime(state.timerRemaining)}</div><div class="grid2"><button class="btn secondary" id="timerToggle">${state.timerId?'一時停止':'スタート'}</button><button class="btn secondary" id="plus30">＋30秒</button></div></div><button class="btn danger full" id="toVote">投票へ</button>`;}
function votePassScreen(){const p=state.players[state.voteIndex];return `${topNav()}${heading('秘密投票',`${state.voteIndex+1} / ${state.playerCount}`)}<div class="privacy-screen"><div><div class="avatar large">${p.icon}</div><h2>${esc(p.name)}さんに<br>スマホを渡してください</h2><p>投票内容はほかの人に見せないでね。</p><button class="btn yellow hold" id="holdVote">長押しして投票</button></div></div>`;}
function voteScreen(){const v=state.voteIndex;return `${topNav()}${heading(`${esc(state.players[v].name)}さんの投票`,'自分以外の1人を選んでください')}<div class="card vote-grid">${state.players.map((p,i)=>i===v?'':`<button class="btn choice vote-choice" data-vote="${i}"><span class="avatar">${p.icon}</span><span>${esc(p.name)}</span></button>`).join('')}</div>`;}
function calcResult(){const counts=Array(state.playerCount).fill(0);state.votes.forEach(v=>counts[v]++);const max=Math.max(...counts);const expelled=max<=1?[]:counts.map((c,i)=>c===max?i:-1).filter(i=>i>=0);const fakeExists=state.finalRoles.includes('fake'),fakeExpelled=expelled.some(i=>state.finalRoles[i]==='fake');if(!fakeExists&&expelled.length===0)return{kind:'peace',winner:'平和なクラス！',reason:'ニセ転校生がいないことを見抜き、だれも処刑されませんでした。',logo:'../../result_peaceful_class.png',expelled,max};const realWin=fakeExists&&fakeExpelled;return{kind:realWin?'real':'fake',winner:realWin?'ホンモノサイド勝利！':'ニセモノサイド勝利！',reason:fakeExists?(fakeExpelled?'ニセ転校生を見つけました。':'ニセ転校生が正体を隠し切りました。'):'ニセ転校生がいないのに、だれかが処刑されました。',logo:realWin?'../../result_honmono_side_win.png':'../../result_nisemono_side_win.png',expelled,max};}
function resultScreen(){const r=calcResult(),names=r.expelled.length?r.expelled.map(i=>state.players[i].name).join('、'):'だれも処刑されませんでした';return `${topNav()}<div class="card result-hero"><img class="result-logo" src="${r.logo}" alt="${r.winner}"><p class="result-reason">${r.reason}</p></div><div class="card"><h2>最終役職</h2>${state.players.map((p,i)=>{const b=state.initialRoles[i],a=state.finalRoles[i];return `<div class="result-role"><div class="avatar">${p.icon}</div><div><strong>${esc(p.name)}</strong><br>${b===a?ROLE_DEFS[a].name:`<span class="strike">${ROLE_DEFS[b].name}</span> → <strong>${ROLE_DEFS[a].name}</strong>`}</div><img class="result-mini" src="${ROLE_DEFS[a].image}" alt="${ROLE_DEFS[a].name}"></div>`}).join('')}</div><div class="card"><h2>投票結果</h2><p>最多票：${r.max}票</p><p><strong>${esc(names)}</strong></p></div><div class="stack"><button class="btn full" id="restartSame">同じメンバーでもう一度</button><button class="btn secondary full" id="restartAll">最初から</button></div>`;}
function startGame(){const d=[];Object.entries(state.roleCounts).forEach(([r,n])=>{for(let i=0;i<n;i++)d.push(r);});state.deck=shuffle(d);state.initialRoles=state.deck.slice(0,state.playerCount);state.finalRoles=[...state.initialRoles];state.rest=state.deck.slice(state.playerCount);state.revealIndex=state.nightIndex=state.voteIndex=0;state.votes=[];state.timerRemaining=state.timerSeconds;go('revealPass');}
function queueCover(n){state.coverNext=n;state.screen='cover';render();} function nextReveal(){if(++state.revealIndex>=state.playerCount)go('nightIntro');else go('revealPass');} function nextNight(){if(++state.nightIndex>=state.playerCount){state.timerRemaining=state.timerSeconds;go('discussion');}else go('nightPass');} function nextVote(){if(++state.voteIndex>=state.playerCount)go('result');else go('votePass');}
function openModal(t){state.modal=t;renderModal();} function closeModal(){document.querySelector('.modal-backdrop')?.remove();state.modal=null;} function renderModal(){document.querySelector('.modal-backdrop')?.remove();const w=document.createElement('div');w.className='modal-backdrop';const content=state.modal==='roles'?`<h2>役職の内容</h2>${roleKeys.map(k=>{const d=ROLE_DEFS[k];return `<div class="role-help"><img src="${d.image}" alt=""><div><strong>${d.name}</strong><div><span class="side-tag ${d.side}">${sideLabel(k)}</span></div><p>${d.desc}</p></div></div>`}).join('')}`:`<h2>今回のレギュ</h2><p>${state.playerCount}人 ＋ お休み2枚</p>${roleKeys.filter(k=>state.roleCounts[k]>0).map(k=>`<div class="reg-line"><span>${ROLE_DEFS[k].name}</span><span>× ${state.roleCounts[k]}</span></div>`).join('')}`;w.innerHTML=`<div class="modal">${content}<button class="btn full" id="closeModal">閉じる</button></div>`;document.body.appendChild(w);document.getElementById('closeModal').addEventListener('click',closeModal);}
function bindHold(id,cb){const el=document.getElementById(id);if(!el)return;let t=null;const start=e=>{e.preventDefault();t=setTimeout(()=>{t=null;cb();},700)},cancel=()=>{if(t){clearTimeout(t);t=null;}};el.addEventListener('pointerdown',start);['pointerup','pointerleave','pointercancel'].forEach(x=>el.addEventListener(x,cancel));}
function toggleTimer(){if(state.timerId){stopTimer();render();return;}state.timerId=setInterval(()=>{state.timerRemaining=Math.max(0,state.timerRemaining-1);const el=document.getElementById('timer');if(el){el.textContent=formatTime(state.timerRemaining);el.classList.toggle('low',state.timerRemaining<=10);}if(state.timerRemaining===0){stopTimer();const b=document.getElementById('timerToggle');if(b)b.textContent='終了';}},1000);render();}
function bind(){
  document.getElementById('startSetup')?.addEventListener('click',()=>go('count'));document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.open)));
  document.querySelectorAll('[data-count]').forEach(b=>b.addEventListener('click',()=>{state.playerCount=Number(b.dataset.count);ensurePlayers();setBaseRoles();render();}));document.getElementById('toPlayers')?.addEventListener('click',()=>{ensurePlayers();go('players')});document.getElementById('backCount')?.addEventListener('click',()=>go('count'));
  document.querySelectorAll('[data-name]').forEach(x=>x.addEventListener('input',()=>{const i=Number(x.dataset.name);state.players[i].name=x.value.trim()||`プレイヤー${i+1}`;}));document.querySelectorAll('[data-icon-player]').forEach(b=>b.addEventListener('click',()=>{state.players[Number(b.dataset.iconPlayer)].icon=b.dataset.icon;render();}));document.getElementById('toRoles')?.addEventListener('click',()=>go('roles'));document.getElementById('backPlayers')?.addEventListener('click',()=>go('players'));
  document.querySelectorAll('[data-role-minus]').forEach(b=>b.addEventListener('click',()=>{const r=b.dataset.roleMinus;if(state.roleCounts[r]>0)state.roleCounts[r]--;render();}));document.querySelectorAll('[data-role-plus]').forEach(b=>b.addEventListener('click',()=>{const r=b.dataset.rolePlus;if(state.roleCounts[r]<ROLE_DEFS[r].max)state.roleCounts[r]++;render();}));document.getElementById('dealRoles')?.addEventListener('click',startGame);
  bindHold('holdReveal',()=>go('revealRole'));document.getElementById('hideRole')?.addEventListener('click',()=>queueCover('revealNext'));document.getElementById('coverNext')?.addEventListener('click',()=>{const n=state.coverNext;state.coverNext=null;if(n==='revealNext')nextReveal();else if(n==='nightNext')nextNight();else if(n==='voteNext')nextVote();});
  document.getElementById('beginNight')?.addEventListener('click',()=>{state.nightIndex=0;go('nightPass')});bindHold('holdNight',()=>go('nightAction'));document.getElementById('nightDone')?.addEventListener('click',()=>queueCover('nightNext'));
  document.getElementById('presidentPlayer')?.addEventListener('click',()=>{const me=state.nightIndex,p=document.querySelector('.card.stack');p.innerHTML=`<h2>1人選ぶ</h2><div class="grid2">${state.players.map((x,i)=>i===me?'':`<button class="btn choice" data-pres-see="${i}">${esc(x.name)}</button>`).join('')}</div>`;document.querySelectorAll('[data-pres-see]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.presSee),r=state.initialRoles[i];p.innerHTML=`<div class="role-reveal"><p>${esc(state.players[i].name)}さんの役職</p><img class="role-card-large" src="${ROLE_DEFS[r].image}" alt="${ROLE_DEFS[r].name}"><button class="btn full" id="nightDone">確認した</button></div>`;document.getElementById('nightDone').addEventListener('click',()=>queueCover('nightNext'));}));});
  document.getElementById('presidentRest')?.addEventListener('click',()=>{const p=document.querySelector('.card.stack');p.innerHTML=`<div class="role-reveal"><h2>お休みのカード</h2><div class="grid2">${state.rest.map(r=>`<img class="role-card-large" src="${ROLE_DEFS[r].image}" alt="${ROLE_DEFS[r].name}">`).join('')}</div><button class="btn full" id="nightDone">確認した</button></div>`;document.getElementById('nightDone').addEventListener('click',()=>queueCover('nightNext'));});
  let observed=[];document.querySelectorAll('[data-observe]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.observe);if(observed.includes(i)){observed=observed.filter(x=>x!==i);b.classList.remove('selected');}else if(observed.length<2){observed.push(i);b.classList.add('selected');}const c=document.getElementById('observerCheck');if(c)c.disabled=observed.length!==2;}));document.getElementById('observerCheck')?.addEventListener('click',()=>{const same=ROLE_DEFS[state.initialRoles[observed[0]]].side===ROLE_DEFS[state.initialRoles[observed[1]]].side,p=document.querySelector('.card.stack');p.innerHTML=`<div class="role-reveal"><h2>${same?'同じサイドです':'ちがうサイドです'}</h2><p>${esc(state.players[observed[0]].name)}さん と ${esc(state.players[observed[1]].name)}さん</p><button class="btn full" id="nightDone">確認した</button></div>`;document.getElementById('nightDone').addEventListener('click',()=>queueCover('nightNext'));});
  document.querySelectorAll('[data-swap]').forEach(b=>b.addEventListener('click',()=>{const t=Number(b.dataset.swap),me=state.nightIndex;[state.finalRoles[me],state.finalRoles[t]]=[state.finalRoles[t],state.finalRoles[me]];const r=state.finalRoles[me],p=document.querySelector('.card.stack');p.innerHTML=`<div class="role-reveal"><h2>${esc(state.players[t].name)}さんと交換しました</h2><p>あなたの新しい役職</p><img class="role-card-large" src="${ROLE_DEFS[r].image}" alt="${ROLE_DEFS[r].name}"><p class="role-desc">交換された相手には、交換されたことは知らされません。</p><button class="btn full" id="nightDone">確認した</button></div>`;document.getElementById('nightDone').addEventListener('click',()=>queueCover('nightNext'));}));document.getElementById('noSwap')?.addEventListener('click',()=>queueCover('nightNext'));
  document.getElementById('timerToggle')?.addEventListener('click',toggleTimer);document.getElementById('plus30')?.addEventListener('click',()=>{state.timerRemaining+=30;render();});document.getElementById('toVote')?.addEventListener('click',()=>{stopTimer();state.voteIndex=0;state.votes=[];go('votePass');});bindHold('holdVote',()=>go('vote'));document.querySelectorAll('[data-vote]').forEach(b=>b.addEventListener('click',()=>{state.votes[state.voteIndex]=Number(b.dataset.vote);queueCover('voteNext');}));
  document.getElementById('restartSame')?.addEventListener('click',()=>go('roles'));document.getElementById('restartAll')?.addEventListener('click',()=>{state.players=[];state.playerCount=3;setBaseRoles();go('title');});
}
setBaseRoles();ensurePlayers();render();