(()=>{
const app=document.getElementById('app');
const DB=window.KANKAKU_QUESTIONS||{};
const playersApi=window.HoukagoPlayers;
const CUSTOM_KEY='houkago_kankaku_custom_v1';
const LONG_PRESS_MS=550;
const state={screen:'title',playerCount:playersApi?.load?.().activeCount||4,players:[],difficulty:'normal',selectedCategories:new Set(Object.keys(DB)),includeCustom:false,roundCount:5,round:0,used:new Set(),topic:null,numbers:[],revealIndex:0,order:[],selectedOrder:null,roundScore:0,totalScore:0,history:[],gameStarted:false};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function loadPlayers(){const d=playersApi?.load?.();if(d){state.playerCount=d.activeCount;state.players=d.players.slice(0,d.activeCount)}else{state.players=Array.from({length:state.playerCount},(_,i)=>({name:'プレイヤー'+(i+1),icon:'●'}))}}
function customItems(){try{const x=JSON.parse(localStorage.getItem(CUSTOM_KEY)||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
function saveCustom(x){try{localStorage.setItem(CUSTOM_KEY,JSON.stringify(x))}catch(e){}}
function topNav(){return '<nav class="top-nav"><button class="nav-pill" data-back>← 戻る</button><button class="nav-pill" data-home>ゲーム一覧</button></nav>'}
function heading(t,p=''){return '<header class="screen-heading"><h1>'+esc(t)+'</h1>'+(p?'<p>'+esc(p)+'</p>':'')+'</header>'}
function memberChip(p){return '<span class="member-chip">'+esc(p.icon)+' '+esc(p.name)+'</span>'}
function allTopics(){const built=[...state.selectedCategories].flatMap(cat=>(DB[cat]||[]).map(x=>({category:cat,q:x[0],low:x[1],high:x[2]})));const custom=state.includeCustom?customItems().map(x=>({category:'マイお題',...x})):[];return [...built,...custom]}
function drawTopic(){let pool=allTopics().filter(x=>!state.used.has(x.category+'|'+x.q));if(!pool.length){state.used.clear();pool=allTopics()}if(!pool.length)return null;const q=pool[Math.floor(Math.random()*pool.length)];state.used.add(q.category+'|'+q.q);return q}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function generateNumbers(n,d){let arr=[];if(d==='easy'){for(let i=0;i<n;i++){const base=Math.round((i+1)*100/(n+1));const jitter=Math.floor(Math.random()*7)-3;arr.push(Math.max(1,Math.min(100,base+jitter)))}arr=[...new Set(arr)];while(arr.length<n){const v=1+Math.floor(Math.random()*100);if(!arr.includes(v))arr.push(v)}}else if(d==='hard'){const span=Math.min(42,Math.max(22,n*5));const start=1+Math.floor(Math.random()*(100-span));while(arr.length<n){const v=start+Math.floor(Math.random()*(span+1));if(!arr.includes(v))arr.push(v)}}else{while(arr.length<n){const v=1+Math.floor(Math.random()*100);if(!arr.includes(v))arr.push(v)}}return shuffle(arr)}
function titleScreen(){return '<section class="title-card"><img class="title-logo" src="../../kankaku_meter_logo_transparent.png" alt="感覚メーター！"><p>数字は言っちゃダメ。ことばの感覚だけで、みんなの順番をそろえよう！</p><div class="stack"><button class="btn yellow full" data-start-title>ゲームをはじめる</button><button class="btn glass full" data-rules>あそびかた</button><button class="btn glass full" data-custom>マイお題</button></div></section>'}
function setupScreen(){loadPlayers();return topNav()+heading('ゲーム設定','3〜10人で、みんなで協力！')+'<section class="card"><h2>参加メンバー</h2><p>'+state.playerCount+'人で遊びます</p><div class="member-chips">'+state.players.map(memberChip).join('')+'</div><div class="count-grid">'+Array.from({length:8},(_,i)=>i+3).map(n=>'<button class="choice-chip '+(n===state.playerCount?'selected':'')+'" data-count="'+n+'">'+n+'人</button>').join('')+'</div></section><section class="card"><h2>難易度</h2><p>数字の離れ具合が変わります。</p><div class="difficulty-grid">'+[['easy','かんたん','数字が離れやすい'],['normal','ふつう','完全ランダム'],['hard','むずかしい','近い数字も出る']].map(x=>'<button class="difficulty-btn '+(state.difficulty===x[0]?'selected':'')+'" data-difficulty="'+x[0]+'">'+x[1]+'<small>'+x[2]+'</small></button>').join('')+'</div></section><button class="btn full" data-next-categories>ジャンル設定へ</button>'}
function categoriesScreen(){const cats=Object.keys(DB),customN=customItems().length,pool=allTopics().length;return topNav()+heading('ジャンル','遊びたいお題を選ぼう')+'<section class="card"><div class="section-row"><div><h2>お題ジャンル</h2><p>複数選べます</p></div><button class="small-btn" data-all>全部</button></div><div class="category-grid">'+cats.map(c=>'<button class="category-chip '+(state.selectedCategories.has(c)?'selected':'')+'" data-cat="'+esc(c)+'">'+esc(c)+'</button>').join('')+'</div></section><section class="card"><div class="section-row"><div><h2>マイお題</h2><p>保存中 '+customN+'問</p></div><button class="small-btn" data-custom>編集</button></div><label class="switch-row '+(!customN?'disabled':'')+'"><input type="checkbox" data-custom-toggle '+(state.includeCustom&&customN?'checked':'')+' '+(!customN?'disabled':'')+'><span>オリジナルお題も混ぜる</span></label></section><p style="text-align:center;color:#667085;font-size:12px;font-weight:800">この設定のお題：<strong data-pool>'+pool+'問</strong></p><button class="btn full" data-begin '+(pool?'':'disabled')+'>5ラウンドでスタート</button>'}
function topicScreen(){const q=state.topic;return topNav()+heading((state.round+1)+' / '+state.roundCount+'ラウンド','まずは全員でお題を確認')+'<section class="card topic-card"><span class="topic-tag">'+esc(q.category)+'</span><h2>'+esc(q.q)+'</h2><div class="scale-box"><div class="scale-end low"><small>1</small>'+esc(q.low)+'</div><div class="scale-arrow">→</div><div class="scale-end high"><small>100</small>'+esc(q.high)+'</div></div></section><button class="btn full" data-secret-start>秘密の数字を見る</button>'}
function passScreen(){const p=state.players[state.revealIndex];return '<section class="privacy-card"><div class="avatar">'+esc(p.icon)+'</div><h2>'+esc(p.name)+'さんに<br>スマホを渡してね</h2><p>ほかの人は画面を見ないでください。</p><button class="btn yellow hold-btn" data-hold><i></i><span>長押しして数字を見る</span></button></section>'}
function numberScreen(){const p=state.players[state.revealIndex],q=state.topic,n=state.numbers[state.revealIndex];return '<section class="number-card"><div class="avatar">'+esc(p.icon)+'</div><strong>'+esc(p.name)+'さんの数字</strong><div class="secret-number">'+n+'</div><div class="number-scale">1 ←────→ 100</div><div class="number-tip">お題「'+esc(q.q)+'」に合わせて、この数字くらいだと思う答えを口頭で考えてね。数字そのものは言わないで！</div><button class="btn full" data-remember>覚えた！</button></section>'}
function readyScreen(){return '<section class="ready-screen"><div class="done-icon">✓</div><h1>全員、数字を<br>確認しました！</h1><p>ここからはみんなで画面を見てOK。<br>一人ずつ、お題に合う答えを口頭で発表してね。</p><button class="btn yellow full" data-arrange>並べる画面へ</button></section>'}
function arrangeScreen(){const q=state.topic;return topNav()+heading('みんなで順番を決めよう','上が小さい数字、下が大きい数字')+'<section class="card topic-card arrange-topic" style="padding:14px"><span class="topic-tag">'+esc(q.category)+'</span><h2 style="font-size:22px;margin:8px 0">'+esc(q.q)+'</h2><div class="arrange-scale"><div class="arrange-scale-end low"><small>1</small><strong>'+esc(q.low)+'</strong></div><div class="arrange-scale-arrow">↓</div><div class="arrange-scale-end high"><small>100</small><strong>'+esc(q.high)+'</strong></div></div></section><p class="arrange-help">カードを2枚タップすると入れ替え。↑↓でも動かせます。</p><div class="order-axis top"><span>1</span><strong>小さい数字</strong><b>↓</b></div><div class="order-list">'+state.order.map((pi,pos)=>{const p=state.players[pi];return '<div class="order-row '+(state.selectedOrder===pos?'selected':'')+'"><span class="order-rank">'+(pos+1)+'</span><button class="order-person" data-order="'+pos+'">'+esc(p.icon)+' '+esc(p.name)+'</button><button class="move-btn" data-up="'+pos+'" '+(pos===0?'disabled':'')+'>↑</button><button class="move-btn" data-down="'+pos+'" '+(pos===state.order.length-1?'disabled':'')+'>↓</button></div>'}).join('')+'</div><div class="order-axis bottom"><span>100</span><strong>大きい数字</strong></div><button class="btn yellow full" style="margin-top:13px" data-confirm>これで決定！</button>'}
function calculateResult(){const correct=[...state.players.keys()].sort((a,b)=>state.numbers[a]-state.numbers[b]);const rank=new Map(correct.map((p,i)=>[p,i]));const seq=state.order.map(p=>rank.get(p));let inv=0;for(let i=0;i<seq.length;i++)for(let j=i+1;j<seq.length;j++)if(seq[i]>seq[j])inv++;const max=seq.length*(seq.length-1)/2;state.roundScore=max?Math.round(100*(1-inv/max)):100;state.totalScore+=state.roundScore}
function resultScreen(){const correct=[...state.players.keys()].sort((a,b)=>state.numbers[a]-state.numbers[b]);const score=state.roundScore;const msg=score===100?'PERFECT！ 全員の感覚がつながった！':score>=80?'おしい！ かなり合ってる！':score>=55?'いい感じ！ あと少し！':'感覚バラバラ！ それも面白い！';return topNav()+heading((state.round+1)+'ラウンド目の結果',msg)+'<div class="result-score"><strong>'+score+'</strong><span>/ 100点</span></div><section class="card"><h2>正しい順番</h2><div class="reveal-list">'+correct.map((pi,i)=>'<div class="reveal-row"><b>'+(i+1)+'</b><span>'+esc(state.players[pi].icon)+' '+esc(state.players[pi].name)+'</span><strong>'+state.numbers[pi]+'</strong></div>').join('')+'</div><div class="fact">答えに正解はありません。数字に合わせてどんな言葉を選んだか、その違いを楽しむゲームです。</div></section><button class="btn full" data-next-round>'+(state.round+1>=state.roundCount?'最終結果を見る':'次のお題へ')+'</button>'}
function finalScreen(){const max=state.roundCount*100,pct=Math.round(state.totalScore/max*100);const title=pct>=90?'感覚シンクロ部！':pct>=75?'かなり通じ合ってる！':pct>=55?'いいチーム！':'もっと知り合えるかも！';return '<section class="final-screen"><div class="done-icon">★</div><h1>'+esc(title)+'</h1><div class="result-score"><strong>'+state.totalScore+'</strong><span>/ '+max+'点</span></div><p>数字を言わずにここまで合わせられた！<br>もう一度やると、違う感覚が見つかるかも。</p><div class="stack" style="width:min(420px,100%)"><button class="btn yellow full" data-replay>同じ設定でもう一度</button><button class="btn secondary full" data-title>タイトルへ</button></div></section>'}
function rulesScreen(){return topNav()+heading('あそびかた','数字を言わずに、みんなで順番を合わせよう')+'<section class="card"><div class="rule-step"><b>1</b><span>全員でお題と「1〜100」の基準を見る</span></div><div class="rule-step"><b>2</b><span>1人ずつ秘密の数字を確認する</span></div><div class="rule-step"><b>3</b><span>数字は言わず、その数字っぽい答えを口頭で発表する</span></div><div class="rule-step"><b>4</b><span>みんなで相談し、小さい数字だと思う順に並べる</span></div><div class="rule-step"><b>5</b><span>数字を公開！ 5ラウンドの合計点に挑戦</span></div></section><section class="card"><h2>大事なルール</h2><p>「70くらい」「半分より上」など、数字を直接伝える言い方は禁止。答えの理由を話したり、みんなで相談したりするのはOK！</p></section>'}
function customScreen(){const items=customItems();return topNav()+heading('マイお題','自分たちだけの感覚テーマを作ろう')+'<section class="card custom-form"><label>お題<input id="cq" maxlength="60" placeholder="例：旅行で行きたい場所"></label><div class="custom-two"><label>1のイメージ<input id="cl" maxlength="30" placeholder="行きたくない"></label><label>100のイメージ<input id="ch" maxlength="30" placeholder="今すぐ行きたい"></label></div><button class="btn full" data-add-custom>追加する</button></section><section class="card"><h2>保存したお題 '+items.length+'問</h2>'+(items.length?'<div class="custom-list">'+items.map((x,i)=>'<div class="custom-item"><div><strong>'+esc(x.q)+'</strong><span>1：'+esc(x.low)+' / 100：'+esc(x.high)+'</span></div><button data-delete="'+i+'">削除</button></div>').join('')+'</div>':'<p>まだマイお題はありません。</p>')+'</section>'}
function screenHtml(){return({title:titleScreen,setup:setupScreen,categories:categoriesScreen,topic:topicScreen,pass:passScreen,number:numberScreen,ready:readyScreen,arrange:arrangeScreen,result:resultScreen,final:finalScreen,rules:rulesScreen,custom:customScreen}[state.screen]||titleScreen)()}
function render(){app.className='meter-app screen-'+state.screen;app.innerHTML=screenHtml();bind();window.scrollTo({top:0,behavior:'auto'})}
function go(s,{push=true}={}){if(push&&state.screen!==s)state.history.push(state.screen);state.screen=s;render()}
function safeBack(){if(state.gameStarted&&['pass','number','ready','arrange','result'].includes(state.screen)){alert('ラウンド中は前の画面に戻れません。');return}if(state.history.length){state.screen=state.history.pop();render()}else{state.screen='title';render()}}
function refreshPool(){const n=allTopics().length;const el=document.querySelector('[data-pool]');if(el)el.textContent=n+'問';const b=document.querySelector('[data-begin]');if(b)b.disabled=n===0}
function beginGame(){loadPlayers();state.used.clear();state.round=0;state.totalScore=0;state.gameStarted=true;newRound()}
function newRound(){state.topic=drawTopic();if(!state.topic){state.gameStarted=false;go('categories');return}state.numbers=generateNumbers(state.playerCount,state.difficulty);state.revealIndex=0;state.order=shuffle([...state.players.keys()]);state.selectedOrder=null;state.roundScore=0;go('topic',{push:false})}
function remember(){state.revealIndex++;if(state.revealIndex>=state.playerCount)go('ready',{push:false});else go('pass',{push:false})}
function swapOrder(a,b){[state.order[a],state.order[b]]=[state.order[b],state.order[a]];state.selectedOrder=null;render()}
function confirmOrder(){calculateResult();go('result')}
function nextRound(){if(state.round+1>=state.roundCount){state.gameStarted=false;go('final');return}state.round++;newRound()}
function addCustom(){const q=document.getElementById('cq')?.value.trim(),low=document.getElementById('cl')?.value.trim(),high=document.getElementById('ch')?.value.trim();if(!q||!low||!high){alert('お題・1・100のイメージを全部入力してください。');return}const a=customItems();a.push({q,low,high});saveCustom(a);render()}
function bindHold(btn,fn){if(!btn)return;let t=null;const start=()=>{btn.classList.add('holding');t=setTimeout(()=>{t=null;btn.classList.remove('holding');fn()},LONG_PRESS_MS)};const cancel=()=>{if(t)clearTimeout(t);t=null;btn.classList.remove('holding')};btn.addEventListener('pointerdown',start);btn.addEventListener('pointerup',cancel);btn.addEventListener('pointerleave',cancel);btn.addEventListener('pointercancel',cancel);btn.addEventListener('contextmenu',e=>e.preventDefault())}
function bind(){
document.querySelector('[data-back]')?.addEventListener('click',safeBack);
document.querySelector('[data-home]')?.addEventListener('click',()=>{if(!state.gameStarted||confirm('ゲームを途中でやめますか？'))location.href='../'});
document.querySelector('[data-start-title]')?.addEventListener('click',()=>{state.history=[];go('setup',{push:false})});
document.querySelectorAll('[data-rules]').forEach(b=>b.addEventListener('click',()=>go('rules')));
document.querySelectorAll('[data-custom]').forEach(b=>b.addEventListener('click',()=>go('custom')));
document.querySelectorAll('[data-count]').forEach(b=>b.addEventListener('click',()=>{playersApi?.setActiveCount?.(Number(b.dataset.count));loadPlayers();render()}));
document.querySelectorAll('[data-difficulty]').forEach(b=>b.addEventListener('click',()=>{state.difficulty=b.dataset.difficulty;render()}));
document.querySelector('[data-next-categories]')?.addEventListener('click',()=>go('categories'));
document.querySelectorAll('[data-cat]').forEach(b=>b.addEventListener('click',()=>{const c=b.dataset.cat;if(state.selectedCategories.has(c))state.selectedCategories.delete(c);else state.selectedCategories.add(c);b.classList.toggle('selected',state.selectedCategories.has(c));refreshPool()}));
document.querySelector('[data-all]')?.addEventListener('click',()=>{const cats=Object.keys(DB),on=cats.every(c=>state.selectedCategories.has(c));state.selectedCategories=on?new Set():new Set(cats);document.querySelectorAll('[data-cat]').forEach(b=>b.classList.toggle('selected',state.selectedCategories.has(b.dataset.cat)));refreshPool()});
document.querySelector('[data-custom-toggle]')?.addEventListener('change',e=>{state.includeCustom=e.target.checked;refreshPool()});
document.querySelector('[data-begin]')?.addEventListener('click',beginGame);
document.querySelector('[data-secret-start]')?.addEventListener('click',()=>go('pass'));
bindHold(document.querySelector('[data-hold]'),()=>go('number'));
document.querySelector('[data-remember]')?.addEventListener('click',remember);
document.querySelector('[data-arrange]')?.addEventListener('click',()=>go('arrange'));
document.querySelectorAll('[data-order]').forEach(b=>b.addEventListener('click',()=>{const p=Number(b.dataset.order);if(state.selectedOrder==null){state.selectedOrder=p;render()}else if(state.selectedOrder===p){state.selectedOrder=null;render()}else swapOrder(state.selectedOrder,p)}));
document.querySelectorAll('[data-up]').forEach(b=>b.addEventListener('click',()=>{const p=Number(b.dataset.up);if(p>0)swapOrder(p,p-1)}));
document.querySelectorAll('[data-down]').forEach(b=>b.addEventListener('click',()=>{const p=Number(b.dataset.down);if(p<state.order.length-1)swapOrder(p,p+1)}));
document.querySelector('[data-confirm]')?.addEventListener('click',confirmOrder);
document.querySelector('[data-next-round]')?.addEventListener('click',nextRound);
document.querySelector('[data-replay]')?.addEventListener('click',()=>{state.history=[];beginGame()});
document.querySelector('[data-title]')?.addEventListener('click',()=>{state.gameStarted=false;state.history=[];go('title',{push:false})});
document.querySelector('[data-add-custom]')?.addEventListener('click',addCustom);
document.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',()=>{const a=customItems();a.splice(Number(b.dataset.delete),1);saveCustom(a);render()}));
}
loadPlayers();render();
})();